### ISSUE TITLE
Missed the Copy Step in Installation.md

### ISSUE THREAD

**Issue by SunthornK** [TeerapatTrepopsakulsin/ku-polls#67]
I think u forgot to add the copy part .That's why the .env file is not created automatically.  And in sample.env doesn't guide how to get the secret key

**Comment by TeerapatTrepopsakulsin** [comment]
Maybe my instruction is unclear, so I add a commandline for the copy part in the `Installation.md` and add instructions for the secret key in the `sample.env`.
